In [1]:
import torch

In [32]:
# 1. Создайте случайный FloatTensor размера 3x4x5

my_tsr = torch.randint(10, size = (3, 4, 5)).type(torch.FloatTensor)
my_tsr

tensor([[[6., 3., 7., 3., 9.],
         [8., 5., 1., 8., 3.],
         [8., 0., 1., 1., 3.],
         [3., 4., 1., 7., 8.]],

        [[0., 1., 9., 2., 1.],
         [6., 9., 7., 1., 0.],
         [9., 7., 9., 2., 0.],
         [7., 0., 7., 7., 2.]],

        [[2., 0., 4., 5., 9.],
         [4., 3., 1., 3., 3.],
         [2., 5., 8., 8., 7.],
         [0., 4., 1., 6., 1.]]])

In [33]:
# 2. Выведите его форму (shape)

my_tsr.size()

torch.Size([3, 4, 5])

In [34]:
# 3. Приведите его к форме 6х10

my_tsr_rshp = my_tsr.reshape(6, 10)
my_tsr_rshp.size()
my_tsr_rshp

tensor([[6., 3., 7., 3., 9., 8., 5., 1., 8., 3.],
        [8., 0., 1., 1., 3., 3., 4., 1., 7., 8.],
        [0., 1., 9., 2., 1., 6., 9., 7., 1., 0.],
        [9., 7., 9., 2., 0., 7., 0., 7., 7., 2.],
        [2., 0., 4., 5., 9., 4., 3., 1., 3., 3.],
        [2., 5., 8., 8., 7., 0., 4., 1., 6., 1.]])

In [37]:
# 4. Создайте случайный IntTensor размера 10

my_tsr2 = torch.randn(10).type(torch.IntTensor)
my_tsr2

tensor([-1, -1, -2,  0,  0,  0,  0,  0, -1,  0], dtype=torch.int32)

In [40]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

new_tsr = my_tsr_rshp.mul(my_tsr2)
new_tsr

tensor([[ -6.,  -3., -14.,   0.,   0.,   0.,   0.,   0.,  -8.,   0.],
        [ -8.,  -0.,  -2.,   0.,   0.,   0.,   0.,   0.,  -7.,   0.],
        [ -0.,  -1., -18.,   0.,   0.,   0.,   0.,   0.,  -1.,   0.],
        [ -9.,  -7., -18.,   0.,   0.,   0.,   0.,   0.,  -7.,   0.],
        [ -2.,  -0.,  -8.,   0.,   0.,   0.,   0.,   0.,  -3.,   0.],
        [ -2.,  -5., -16.,   0.,   0.,   0.,   0.,   0.,  -6.,   0.]])

In [48]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

(new_tsr @ new_tsr.T).size()

torch.Size([6, 6])

In [68]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad = True)
z = torch.tensor([0.5], requires_grad = True)
t = torch.tensor([2.], requires_grad = True)
y = (x**3) + z - 75*t

print(f'x = {x}')
print(f'z = {z}')
print(f't = {t}')

y.backward()
print('dy/dx: ', x.grad) 
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)


x = tensor([1.], requires_grad=True)
z = tensor([0.5000], requires_grad=True)
t = tensor([2.], requires_grad=True)
dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [71]:
# 8. Создайте единичный тензор размера 5x6
ones_tsr = torch.ones((5,6))
ones_tsr

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [76]:
# 9. Переведите его в формат numpy


ones_tsr_np = ones_tsr.numpy()
ones_tsr_np, type(ones_tsr_np)

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32), numpy.ndarray)